version: '3'

services:
  web_app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - REDIS_HOSTNAME=redis
    volumes:
      - .:/app

    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A 'mysite' worker -l info
    
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - DEBUG=1
      - REDIS_HOSTNAME=redis
    depends_on:
      - redis
      - web_app
